[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.args]
RELEASE_URL = ""

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "./entrypoint.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
