#!/usr/bin/env python3
"""Remove pipeline artifacts (raw, processed, features) for gids NOT in corpus/books.yaml.

After T-FIN-1 dropped 86 SERIOUS rows, the data/raw/, data/processed/, and
data/features/ directories still contain stale entries from prior runs. The
Wave-2 retrain must operate on only the 154 surviving books, otherwise W2V
trains on dropped content and corpus_hash + model state diverges from the
canonical 154-book manifest.

This script reads books.yaml as ground truth and removes any per-book file
whose gid is not in the manifest. It does NOT delete model files (.joblib,
.model, .pkl, .npy at the top of data/models/) — those are regenerated by
the retrain pipeline naturally.

Usage:
    python scripts/clean_stale_pipeline_artifacts.py
"""
from __future__ import annotations

import sys
from pathlib import Path
import re

import yaml


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    books_yaml = repo_root / 'corpus' / 'books.yaml'

    with books_yaml.open() as f:
        d = yaml.safe_load(f)

    keep_gids: set[int] = set()
    for genre_books in d['genres'].values():
        for book in genre_books:
            keep_gids.add(int(book['gutenberg_id']))

    print(f"Books in manifest: {len(keep_gids)}")

    # Remove stale data/raw/{gid}.txt
    raw_dir = repo_root / 'data' / 'raw'
    raw_removed = 0
    if raw_dir.exists():
        for f in sorted(raw_dir.glob('*.txt')):
            try:
                gid = int(f.stem)
            except ValueError:
                continue
            if gid not in keep_gids:
                f.unlink()
                raw_removed += 1
    print(f"Stale raw files removed: {raw_removed}")

    # Remove stale data/processed/{gid}.json
    proc_dir = repo_root / 'data' / 'processed'
    proc_removed = 0
    if proc_dir.exists():
        for f in sorted(proc_dir.glob('*.json')):
            try:
                gid = int(f.stem)
            except ValueError:
                continue
            if gid not in keep_gids:
                f.unlink()
                proc_removed += 1
    print(f"Stale processed files removed: {proc_removed}")

    # Remove stale features:
    # Filename patterns:
    #   diagrams_{gid}_w{N}.npy
    #   diagrams_{gid}_w{N}_adap.npy
    #   tfidf_{gid}_w{N}.npy
    #   vectors_{gid}_w{N}.npy
    #   words_{gid}_w{N}.json
    feat_dir = repo_root / 'data' / 'features'
    feat_removed = 0
    pattern = re.compile(r'^(?:diagrams|tfidf|vectors|words)_(\d+)_w\d+(?:_adap)?\.(?:npy|json)$')
    if feat_dir.exists():
        for f in sorted(feat_dir.iterdir()):
            if not f.is_file():
                continue
            m = pattern.match(f.name)
            if not m:
                continue
            gid = int(m.group(1))
            if gid not in keep_gids:
                f.unlink()
                feat_removed += 1
    print(f"Stale features removed: {feat_removed}")

    return 0


if __name__ == '__main__':
    sys.exit(main())
