"""Unit tests for the four new VALIDATION_PROTOCOL §10 routines in scripts/06_validate.py.

Synthetic small fixtures only — does NOT load the real v2 model artifacts.
Tests ensure shape + determinism + boundary behaviour; the substantive
numeric validation lives in results/v2_validation_report.md generated by main().
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import numpy as np
import pytest


# Dynamic import: scripts/06_validate.py is not a valid Python module name (leading digit),
# so we load it by file path and bind it to a module alias.
_SCRIPT_PATH = Path(__file__).parent / "06_validate.py"
_spec = importlib.util.spec_from_file_location("validate_06", str(_SCRIPT_PATH))
_validate = importlib.util.module_from_spec(_spec)
sys.modules["validate_06"] = _validate
_spec.loader.exec_module(_validate)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

def make_synthetic_corpus(n_books=48, n_features=20, n_genres=8, seed=0):
    """Build a small, well-separated synthetic feature matrix.

    Each genre has its own latent centroid; features are centroid + small noise.
    This guarantees the SVM finds real signal (so per-author smoke tests have a
    non-trivial loocv_acc to compute a gap from).
    """
    rng = np.random.default_rng(seed)
    books_per_genre = n_books // n_genres
    centroids = rng.normal(scale=5.0, size=(n_genres, n_features))

    X = np.zeros((n_books, n_features), dtype=np.float64)
    y = np.zeros(n_books, dtype=np.int64)
    authors = np.empty(n_books, dtype=object)

    gutenberg_ids = []
    for g in range(n_genres):
        for b in range(books_per_genre):
            i = g * books_per_genre + b
            X[i] = centroids[g] + rng.normal(scale=0.5, size=n_features)
            y[i] = g
            # Assign each genre 3 distinct authors (2 books each on avg)
            authors[i] = f"author_{g}_{b // 2}"
            gutenberg_ids.append(1000 + i)

    return X, y, authors, gutenberg_ids


# ---------------------------------------------------------------------------
# Test 1: evaluate_on_holdout
# ---------------------------------------------------------------------------

def test_evaluate_on_holdout_shape_and_keys():
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.feature_selection import VarianceThreshold
    from sklearn.svm import SVC

    X, y, authors, gids = make_synthetic_corpus()

    # Hold out 4 ids (1 per of 4 genres). Train on the remaining 44.
    holdout_ids = [gids[0], gids[6], gids[12], gids[18]]
    holdout_mask = np.array([g in holdout_ids for g in gids])
    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("vt", VarianceThreshold(threshold=1e-4)),
        ("svm", SVC(kernel="rbf", C=10.0, gamma="scale",
                    class_weight="balanced", random_state=42)),
    ])
    pipe.fit(X[~holdout_mask], y[~holdout_mask])

    result = _validate.evaluate_on_holdout(pipe, X, y, gids, holdout_ids)

    for key in ("macro_f1", "per_genre_f1", "accuracy", "confusion_matrix",
                "n_in_comparison", "in_comparison_ids", "out_of_comparison_ids",
                "predictions"):
        assert key in result, f"missing key: {key}"

    assert result["n_in_comparison"] == 4
    assert isinstance(result["macro_f1"], float)
    assert isinstance(result["per_genre_f1"], dict)
    assert isinstance(result["confusion_matrix"], list)
    assert all(isinstance(p, dict) for p in result["predictions"])
    assert len(result["predictions"]) == 4


def test_evaluate_on_holdout_out_of_comparison():
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.svm import SVC

    X, y, authors, gids = make_synthetic_corpus(n_books=16, n_features=10, n_genres=8)
    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("svm", SVC(kernel="rbf", C=10.0, gamma="scale",
                    class_weight="balanced", random_state=42)),
    ])
    pipe.fit(X, y)

    # 2 in-corpus + 2 out-of-corpus
    holdout_ids = [gids[0], gids[5], 999999, 888888]
    result = _validate.evaluate_on_holdout(pipe, X, y, gids, holdout_ids)
    assert result["n_in_comparison"] == 2
    assert set(result["out_of_comparison_ids"]) == {999999, 888888}


# ---------------------------------------------------------------------------
# Test 2: cross_validate_grouped
# ---------------------------------------------------------------------------

def test_cross_validate_grouped_shape():
    X, y, authors, gids = make_synthetic_corpus()
    result = _validate.cross_validate_grouped(X, y, authors, n_splits=4)
    for k in ("mean", "std", "fold_scores", "n_splits_actual"):
        assert k in result
    assert len(result["fold_scores"]) == result["n_splits_actual"]
    assert result["n_splits_actual"] <= 4
    assert 0.0 <= result["mean"] <= 1.0


def test_cross_validate_grouped_deterministic():
    X, y, authors, gids = make_synthetic_corpus()
    r1 = _validate.cross_validate_grouped(X, y, authors, n_splits=4)
    r2 = _validate.cross_validate_grouped(X, y, authors, n_splits=4)
    assert r1["mean"] == r2["mean"]
    assert r1["std"] == r2["std"]
    assert r1["fold_scores"] == r2["fold_scores"]


# ---------------------------------------------------------------------------
# Test 3: per_author_held_out_smoke_test
# ---------------------------------------------------------------------------

def test_per_author_held_out_smoke_test_shape():
    X, y, authors, gids = make_synthetic_corpus()
    result = _validate.per_author_held_out_smoke_test(X, y, authors, loocv_acc=0.8)
    for k in ("per_author_accuracy", "mean_per_author_accuracy",
              "min_per_author_accuracy", "mean_gap_pp", "worst_case_gap_pp",
              "loocv_acc", "pass_threshold_pp", "mean_gap_passes",
              "worst_case_passes", "n_authors_tested"):
        assert k in result
    assert result["pass_threshold_pp"] == 10.0
    assert isinstance(result["per_author_accuracy"], dict)
    assert result["n_authors_tested"] >= 1


def test_per_author_held_out_filters_single_book_authors():
    """Authors with only 1 book in the corpus must NOT participate."""
    X, y, authors, gids = make_synthetic_corpus()
    # Add a single-book ghost author
    X_aug = np.vstack([X, X[:1] + 0.01])
    y_aug = np.append(y, y[0])
    authors_aug = np.append(authors, "ghost_solo_author")
    result = _validate.per_author_held_out_smoke_test(X_aug, y_aug, authors_aug, loocv_acc=0.8)
    assert "ghost_solo_author" not in result["per_author_accuracy"]


# ---------------------------------------------------------------------------
# Test 4: permutation_null_test
# ---------------------------------------------------------------------------

def test_permutation_null_test_shape():
    X, y, authors, gids = make_synthetic_corpus()
    # Use small n_permutations for speed
    result = _validate.permutation_null_test(X, y, n_permutations=20, random_state=42)
    for k in ("observed_macro_f1", "permuted_macro_f1s", "p_value",
              "mean_permuted", "std_permuted", "significant_at_0_05"):
        assert k in result
    assert len(result["permuted_macro_f1s"]) == 20
    assert 0.0 <= result["p_value"] <= 1.0


def test_permutation_null_test_deterministic():
    X, y, authors, gids = make_synthetic_corpus()
    r1 = _validate.permutation_null_test(X, y, n_permutations=20, random_state=42)
    r2 = _validate.permutation_null_test(X, y, n_permutations=20, random_state=42)
    assert r1["observed_macro_f1"] == r2["observed_macro_f1"]
    assert r1["p_value"] == r2["p_value"]
    assert r1["permuted_macro_f1s"] == r2["permuted_macro_f1s"]


# ---------------------------------------------------------------------------
# Test 5: all four functions deterministic (per task spec)
# ---------------------------------------------------------------------------

def test_all_four_functions_deterministic():
    """Re-running with identical inputs returns identical dicts."""
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.feature_selection import VarianceThreshold
    from sklearn.svm import SVC

    X, y, authors, gids = make_synthetic_corpus()

    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("vt", VarianceThreshold(threshold=1e-4)),
        ("svm", SVC(kernel="rbf", C=10.0, gamma="scale",
                    class_weight="balanced", random_state=42)),
    ])
    pipe.fit(X, y)

    holdout_ids = [gids[0], gids[6]]
    a1 = _validate.evaluate_on_holdout(pipe, X, y, gids, holdout_ids)
    a2 = _validate.evaluate_on_holdout(pipe, X, y, gids, holdout_ids)
    assert a1["macro_f1"] == a2["macro_f1"]
    assert a1["per_genre_f1"] == a2["per_genre_f1"]

    b1 = _validate.cross_validate_grouped(X, y, authors, n_splits=4)
    b2 = _validate.cross_validate_grouped(X, y, authors, n_splits=4)
    assert b1 == b2

    c1 = _validate.per_author_held_out_smoke_test(X, y, authors, loocv_acc=0.8)
    c2 = _validate.per_author_held_out_smoke_test(X, y, authors, loocv_acc=0.8)
    assert c1["per_author_accuracy"] == c2["per_author_accuracy"]
    assert c1["mean_gap_pp"] == c2["mean_gap_pp"]

    d1 = _validate.permutation_null_test(X, y, n_permutations=15, random_state=42)
    d2 = _validate.permutation_null_test(X, y, n_permutations=15, random_state=42)
    assert d1["p_value"] == d2["p_value"]
    assert d1["observed_macro_f1"] == d2["observed_macro_f1"]


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
